
name: Update download history

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: download-extractor

      - name: Checkout mod database
        uses: actions/checkout@v3
        with:
          repository: MegaPiggy/smol-ame-mod-database
          ref: main
          fetch-depth: 0
          path: smol-ame-mod-database
          
      - name: Get database log 
        run: |
          cd smol-ame-mod-database
          git log -p > log.txt
          cd ..
        
      - name: Convert log.txt to json
        run: |
          cd download-extractor
          ./bin/Debug/net6.0/SAModDBDownloadCountExtractor.exe "../smol-ame-mod-database/log.txt" > download-history.json
          cd ..
          
      - name: Commit log json
        run: |
          cd download-extractor
          git config --global user.email "db@smolamemods.com"
          git config --global user.name "GH Action"
          git add download-history.json
          git commit -m "Update download history"
          git push
  
